version: '3.9'

services:
  runner:
    image: myoung34/github-runner:latest
    container_name: ${DOCKER_NAME}
    restart: always
    env_file:
      - ../default.env
      - repo.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${RUNNER_WORKDIR}:${RUNNER_WORKDIR}
      - data:/actions-runner

volumes:
  data: